### ISSUE TITLE
libffi error when installing

### ISSUE THREAD

**Issue by raphaelrk** [muxinc/example-ios-live-streaming#12]
Trying to run the `make setup && make pods step` and getting this error

Also happens when trying with #11 

```
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Library/Ruby/Gems/2.3.0/gems/ffi-1.12.1/lib/ffi_c.bundle, 0x0009): symbol '_ffi_type_double' not found, expected in flat namespace by '/Library/Ruby/Gems/2.3.0/gems/ffi-1.12.1/lib/ffi_c.bundle' - /Library/Ruby/Gems/2.3.0/gems/ffi-1.12.1/lib/ffi_c.bundle (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/ffi-1.12.1/lib/ffi.rb:6:in `rescue in <top (required)>'
	from /Library/Ruby/Gems/2.3.0/gems/ffi-1.12.1/lib/ffi.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/ethon-0.12.0/lib/ethon.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/typhoeus-1.3.1/lib/typhoeus.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/sources_manager.rb:5:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/core_overrides.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods.rb:75:in `<module:Pod>'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods.rb:17:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/bin/pod:36:in `<top (required)>'
	from /usr/local/bin/pod:22:in `load'
	from /usr/local/bin/pod:22:in `<main>'
make: *** [setup] Error 1
```

**Comment by raphaelrk** [comment]
Fixed this with some combination of reinstalling xcode, reinstalling rubygems, reinstalling cocoapods, and then installing ffi using gems

**Comment by dylanjha** [comment]
@raphaelrk glad you got it fixed!
